#:kivy 2.0

<AppLayout>
  orientation: "vertical"

  Label:
    text: "Dice Rolling"

  BoxLayout:
    orientation: "horizontal"

    Spinner:
      id: spinner_id
      text: "How many sides?"
      values: ["1", "2", "3", "4", "5", "6"]
      on_text: root.select_sides(spinner_id.text)


    Label:
      id: dice
      text: "Dice Go Here"

  Button:
    text: "Roll Dice"
    on_release: root.roll_dice()